# Generated by Django 3.1.4 on 2020-12-31 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='khaled', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='aqaba', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Department.objects.get(id=1)', max_length=255),
            preserve_default=False,
        ),
    ]
