# Generated by Django 3.1.4 on 2020-12-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201231_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dec',
            field=models.CharField(default='marjeting', max_length=500),
            preserve_default=False,
        ),
    ]
